# Generated by Django 4.2.28 on 2026-03-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('scale', 'Scale')], default='pro', max_length=24)),
                ('payment_brand', models.CharField(default='VISA', max_length=24)),
                ('payment_last4', models.CharField(default='2481', max_length=4)),
                ('payment_expiry', models.CharField(default='08/28', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stancer', max_length=32)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('checkout_url', models.URLField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='eur', max_length=8)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('unknown', 'Unknown')], default='created', max_length=32)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='billing_api.billingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='eur', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('issued_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing_api.paymentintent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing_api.billingprofile')),
            ],
        ),
    ]
