# Generated by Django 4.2.28 on 2026-03-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='payment_brand',
            field=models.CharField(default='Not set', max_length=24),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='payment_expiry',
            field=models.CharField(default='--/--', max_length=7),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='payment_last4',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('scale', 'Scale')], default='starter', max_length=24),
        ),
    ]
